import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'zh_CN': {
      "Please wait..." : "OTA升级准备中,请不要退出该页面...",
      "Password must be between 8 and 16 characters." : "密码需要控制在8-16个字符",
      "Cannot contain invalid characters.":"不能包含非法字符",
      "Tergasy Fitness" : "优创生活健身",
      "Successful updates" : "OTA升级成功",
      "Device disconnected" : "与设备断开连接",
      "Your version is up to date" : "已是最新版本",
      "Location permission required" : "将不能进行蓝牙扫描和连接，请授予开启定位权限",
      "Enable Location services" : "将不能进行蓝牙扫描和连接，请授予开启位置服务",
      "Enable Bluetooth" : "将不能进行蓝牙扫描和连接，请授予开启蓝牙",
      "Enduser Agreement and Privacy Policy" : "用户协议和隐私政策",
      "Thank you for using Tergasy Fitness App.Please read 《"  : "\n请您务必审慎阅读、充分理解“用户协议”和“隐私政策”各条款，包括但不限于：为了向您提供蓝牙连接等服务，我们需要获取您的地理位置等个人信息并管理您的授权。您可阅读《",
      "》 carefully,and click \"OK\" to start using our App." : "》，了解详细信息，如你同意，请点击同意开始接受我们的服务。",
      "OK1" : "同意",
      "Cancel" : "取消",
      "Phone number" : "请输入手机号",
      "Email" : "邮箱登录注册",
      "Password" : "密码登录",
      "Guest" : "访客登录",
      "Others" : "其他登录方式",
      "Phone Number" : "手机登录注册",
      "Input Account" : "请输入手机号/邮箱账号",
      "Verification code" : "请输入验证码",
      "Input Email" : "请输入邮箱账号",
      "Not a member?" : "非会员?",
      "Have an account already?" : "已有账号?",
      "Sign up with the Guest Account" : "访客登录",
      "Get code" : "获取验证码",
      "Loading" : "获取中...",
      "Resend" : "重新发送",
      "PassWord" : "请输入密码",
      "Log in/Register" : "登录/注册",
      "Set time goal" : "输入时间",
      "Set count goal" : "输入次数",
      "Time goal" : "请输入设定时间",
      "Count goal" : "请输入设定次数",
      "Sign Up": "注册",
      "Log in" : "登录",
      "Forgot password" : "忘记密码",
      "Choose verification method" : "选择验证方式",
      "Unregistered user will automatically register and sign in after authentication" : "未注册的用户验证后将自动注册并登录",
      "By registering,you agree to the" : "登录即代表你同意",
      "Loading2" : "正在加载...",
      "request failed" : "获取验证码失败",
      "incorrectIDorPassword" : "账号或密码错误，请重新输入。",
      "No password set" : "没有设置密码",
      "Account does not exist" : "账号不存在",
      "Account disabled" : "账号被禁用",
      "Improve personal information" : "完善个人资料",
      "Improving information make sports data more accurate" : "完善资料让运动健康数据更准确",
      "Name" : "给自己取个名字吧",
      "Date of birth" : "生日",
      "Height" : "身高",
      "Weight" : "体重",
      "OK2" : "确定",
      "Finish" : "完成",
      "Take photo" : "拍照",
      "Select image" : "相册",
      "Welcome back" : "欢迎回来,",
      "let's start exercising!" : "开始运动！",
      "Home" : "首页",
      "Search devices" : "发现设备",
      "Not Device" : "未发现到设备，请重试",
      "Retry" : "立即重试",
      "Searching" : "设备扫描中…",
      "Available devices" : "可用设备",
      "Connecting" : "设备连接中…",
      "Connect failed" : "设备连接失败，请重新连接",
      "Press again to exit" : "再按一次退出",
      "No motion data" : "这里什么都没留下",
      "The email is already linked.Please enter another one." : "该邮箱已被其他账号绑定",
      "The phone is already linked.Please enter another one." : "该手机号已被其他账号绑定",
      "Incorrect verification code" : "验证码错误",
      "Time must be between 1 and 60 minutes." : "设定时长需限制在1至60分钟",
      "Count must be between 1 and 9999." : "设定次数需限制在1至9999个",
      "Status" : "统计",
      "My data" : "我的数据统计",
      "All Time" : "总",
      "Day" : "日",
      "Week" : "周",
      "Month" : "月",
      "Exercise data" : "运动数据",
      "All data" : "全部",
      "Duration" : "时长",
      "Consume" : "消耗",
      "Strength" : "强度",
      "Sports calendar" : "运动日历",
      "Graph" : "曲线图",
      "Units" : "单位",
      "All Device" : "全部设备",
      "Jump rope" : "跳绳",
      "Resistance Band" : "拉力绳",
      "Spider Resistance Band" : "蝴蝶绳",
      "Dumbbell" : "哑铃",
      "AB Wheel" : "健腹轮",
      "LeaderBoard" : "排行榜",
      "Place" : "名",
      "me" : "我的",
      "Profile" : "个人资料",
      "Settings" : "运动设置",
      "Version" : "软件版本",
      "Nick name" : "用户名",
      "Gender" : "性别",
      "Male" : "男",
      "Female" : "女",
      "Account amd security" : "账号与安全",
      "Modify nick name" : "修改用户名",
      "Input nickname" : "请输入用户名",
      "Save" : "保存",
      "set" : "个数",
      // "Lets go" : "开始运动吧！",
      "Come on" : "加油",
      "My exercise data" : "我的运动数据",
      "count" : "运动个数",
      "duration" : "运动时长",
      "Top coach" : "金牌教练",
      "lock" : "锁定",
      "Unlock" : "解锁",
      "Speaking" : "播报中",
      "Silence" : "静音中",
      "Select mode" : "选择模式",
      "OTA" : "固件升级",
      "Setting" :"运动设置",
      "Screen mirroring" : "电视投屏",
      "Edit" : "编辑卡片",
      "Show" : "显示卡片",
      "Hold and drag to change the order" : "长按拖动调整卡片顺序",
      "Speak" : "语音播报",
      "speak count of exercise" : "按运动个数播报",
      "frequency" : "个数频率",
      "Select Mode" : "模式选择",
      "Train Mode" : "请选择训练模式",
      "Free mode" : "自由模式",
      "Time training" : "定时计数",
      "Count training" : "定数计时",
      "customize" : "自定义",
      "select type" : "请选择训练类型",
      "minute" : "分钟",
      "minutes" : "分钟",
      "Kneeling" : "跪姿卷腹",
      "Standing" : "站姿卷腹",
      "Dumbbell curl" : "哑铃弯举",
      "Bent arm flexion and extension" : "俯身臂屈伸",
      "Neck flexion and extension" : "颈后臂屈伸",
      "Leaning over rowing" : "弯腰划船",
      "Free skipping" : "自由跳绳",
      "Standing rowing" : "站姿划船",
      "Upward curl" : "向上弯举",
      "Side lift" : "侧平举",
      "Overhead flexion and extension" : "过顶屈伸",
      "Supine rowing" : "仰卧划船",
      "Sitting curl" : "坐姿弯举",
      "Seated row" : "坐姿划船",
      "Count" : "本次运动个数",//英文count
      "Calories" : "消耗卡路里",
      "Exercise intensity" : "运动强度",
      "Average speed" : "平均速度",
      "Maximum heart rate" : "最大心率",
      "Minimum heart rate" : "最小心率",
      "Heart rate graph" : "心率曲线图",
      "Offline data has no real-time heart rate" : "离线数据没有实时心率显示",
      "No real-time heart rate this time" : "本次运动没有记录到实时心率",
      "Average heart rate" : "平均心率",
      "Exercise records" : "历史记录",
      "Select all" : "全选",
      "Delete" : "删除",
      "Linked" : "已绑定",
      "None" : "未绑定",
      "Link" : "绑定",
      "Change" : "更改",
      "Phone" : "手机号",
      "Change password" : "设置密码",
      "Delete account" : "注销账号",
      "LOG OUT" : "退出登录",
      "It seems that there is no internet" : "咦好像没有网络",
      "Refresh" : "刷新",
      "success" : "操作成功",
      "Jump to the homepage in" : "跳转首页倒计时：",
      "Return now" : "立即返回",
      "Reset password" : "重置密码",
      "New password" : "请输入新密码",
      "Confirm password" : "请确认新密码",
      "Passwords do not match.Try again." : "两次密码不一致，请重新输入",
      "Mobile phone number verification" : "手机号验证",
      "For your account security, you need to verify your phone number" : "为了您的账户安全，需要验证您的手机号",
      "Next" : "下一步",
      "Link phone number" : "绑定手机号",
      "Link new phone number" : "绑定新手机号",
      "Link email" : "绑定邮箱账号",
      "Link new email" : "绑定新邮箱账号",
      "E-mail verification" : "邮箱验证",
      "For your account security, you need to verify your Email" : "为了您的账户安全，需要验证您的邮箱",
      "power" : "力量",
      "agility" : "敏捷",
      "endurance" : "耐力",
      "perseverance" : "毅力",
      "physique" : "体质",
      "data graph" : "战斗力数据图",
      "monday" : "星期一",
      "tuesday" : "星期二",
      "wednesday" : "星期三",
      "thursday" : "星期四",
      "friday" : "星期五",
      "saturday" : "星期六",
      "sunday" : "星期日",
      "year" : "年",
      "singleCount" : "次",
      "heartRate" : "心率",
      "clickToLogin" : "点击登录查看",
      "unloggedIn" : "未登录",
      "notSet" : "未设置",
      "seted" : "已设置",
      "mistakeInfo" : "账号或者密码错误",
      "disableAccount" : "账号被禁用",
      "logoutTips" : "本次注销账号将会删除全部用户信息以及全部历史运动记录，是否要进行账号注销?",
      "notSaveRecord" : "本次结束运动不保存记录",
      "isEndSport" : "确定要结束运动吗",
      "registerByPhone" : "手机号登录注册",
      "registerByEmail" : "邮箱登录注册",
      "registerByPassword" : "密码登录",
      "setting" : "设置",
      "signOutTips" : "确定要退出登录吗?",
      "deleteRecord" : "确定要删除运动记录吗?",
      "jumpRope" : "智能蓝牙跳绳 SJ100",
      "resistanceBand" : "智能蓝牙拉力绳 SR100",
      "spiderBand" : "智能蓝牙蝴蝶拉力环 SS100",
      "dumbBell" : "智能蓝牙哑铃 SY100",
      "abWheel" : "智能蓝牙健腹轮 SW100",
      "grip" : "智能蓝牙握力环 SJ200",
      "Grip" : "握力环",
      "SJ500" : "智能语音跳绳 SJ500",
      "headJumpRpoe" : "智能语音跳绳 NT930",
      "jumpRope200" : "智能蓝牙跳绳 SJ200",
      'fasciaGun' :'智能筋膜枪 FG100',
      "selectcountryregion" : "选择国家和地区",
      "validEmail" : "请输入正确的邮件地址",
      "Invalid number" : "请输入正确的手机号码",
      "OTAtips":"正在OTA升级中，请不要切换或者退出页面",
      "Operation failed" : "操作失败，请重试",
      "All history" :  "全部数据",
      "agreeToService": "请同意用户协议和隐私政策",
      'blueService' : '为了发现和添加设备，优创生活健身需要开启蓝牙服务',
      'localPermission' : '为了发现和添加设备，优创生活健身需要开启位置权限',
      'localService' : '为了发现和添加设备，优创生活健身需要开启位置服务',
      'otetip': '是否要进行OTA升级',
      'otaVersionTip': '网络不好，固件版本获取失败',
      'head-SR105': '智能蓝牙跳绳 SR105',
      'reSendData' : '网络出错，运动数据上次失败，是否重新上传',
      'update failed' : '更新失败',
      'medal' : '勋章',
      'completion' : '已获得',
      'incomplete' : '尚未获得',
      'Medal Details' : '勋章详情',
      'deviceTypeError' : '请匹配正确的设备类型',
      'wrong device type' : '设备类型错误',
      'tips' : '温馨提示',
    },
    'en_US': {
      'tips' : 'Tips',
      'wrong device type' : 'Wrong Device Type',
      'deviceTypeError' : 'Please match the correct device type',
      'Medal Details' : 'Medal Details',
      'completion' : 'completion',
      'incomplete' : 'incomplete',
      'medal' : 'Medal',
      'update failed' : 'Update failed',
      'reSendData' : 'The network is not good，so that exercise data failed last time, whether to upload again',
      'head-SR105': 'Smart Jump Rope SR105',
      'otaVersionTip': 'The network is not good, and the firmware version failed to be obtained',
      'otetip': 'Do you want to perform a firmware upgrade',
      'blueService' : 'The UCfitness app needs to enable Bluetooth to discover and add devices',
      'localPermission' : 'In order to discover and add devices, the UCfitness app needs to enable location permissions',
      'localService' : 'In order to discover and add devices, the UCfitness app needs to enable location services',
      "agreeToService": 'Please read and agree to the Enduser Agreement and Privacy Policy',
      "Successful updates": "OTA upgrade completed",
      "Device disconnected": "Device disconnected",
      "Please wait...": "Please do not quit the page while OTA upgrade is in preparation…",
      "Your version is up to date": "Your version is up to date",
      "Location permission required": "Bluetooth scanning and connection are not available, please enable location access.",
      "Enable Location services": "Bluetooth scanning and connection are not available, please enable location services",
      "Enable Bluetooth": "Bluetooth scanning and connection are not available, please enable Bluetooth",
      "Enduser Agreement and Privacy Policy" : "Enduser Agreement and Privacy Policy",
      "Thank you for using Tergasy Fitness App.Please read 《" : "\nThank you for using UCfitness App.Please read 《",
      "》 carefully,and click \"OK\" to start using our App." : "》 carefully,and click \"OK\" to start using our App.",
      "OK1" : "OK",
      "Cancel" : "Cancel",
      "Tergasy Fitness" : "UCfitness",
      "Phone number" : "Phone number",
      "Email" : "Email login registration",
      "Password" : "Password log in",
      "Guest" : "Guest log in",
      "Others" : "Other log in methods",
      "Phone Number" : "Mobile login registration",
      "Verification code" : "Verification code",
      "Input Email" :"Email Address",
      "Input Account" : "Phone/Email",
      "Get code" : "Get code",
      "incorrectIDorPassword" : "Incorrect ID or password.",
      "request failed" : "Failed to get verification code",
      "Loading" : "Loading",
      "Resend" : "Resend",
      "PassWord" : "Password",
      "Log in/Register" : "Log in / Register",
      "Not a member?" : "Not a member?",
      "Have an account already?" : "Have an account already?",
      "Sign up with the Guest Account" : "Sign up with the Guest Account",
      "Set time goal" : "Set time goal",
      "Set count goal" : "Set count goal",
      "Time goal" :  "Input target time",
      "Count goal" :  "Input target counts",
      "Sign Up":  "Sign Up",
      "Log in" :  "Log In",
      "Forgot password" :  "Forgot password",
      "Unregistered user will automatically register and sign in after authentication" :  "Non-registered users will be automatically registered and logged in after verification",
      "By registering,you agree to the" :  "Log in means you agree to the ",
      "Loading2" :  "Loading...",
      "No password set" :  "No password set",
      "Account does not exist" :  "Account does not exist",
      "Account disabled" :  "Account disabled",
      "Press again to exit" :  "Press again to exit",
      "No motion data" :  "Nothing here",
      "Improve personal information" :  "Complete your profile",
      "Improving information make sports data more accurate" :  "Complete your profile for more accurate exercise and health data",
      "Name" :  "Name yourself",
      "Date of birth" :  "Date of birth",
      "Height" :  "Height",
      "Weight" :  "Weight",
      "OK2" :  "OK",
      "Finish" :  "Finish",
      "Take photo" :  "Take photo",
      "Select image" :  "Select image",
      "The email is already linked.Please enter another one." :  "The email is already linked.Please enter another one.",
      "The phone is already linked.Please enter another one." :  "The phone is already linked.Please enter another one.",
      "Welcome back" :  "Welcome back,",
      "let's start exercising!" :  "Let's start exercising!",
      "Home" :  "Home",
      "Search devices" :  "Find device",
      "Not Device" :  "No device found, please try again",
      "Retry" :  "Retry now",
      "Searching" :  "Scanning device...",
      "Available devices" :  "Available devices",
      "Connecting" :  "Connecting…",
      "Connect failed" :  "Device connection failed, please reconnect",
      "Status" :  "Statistics",
      "My data" :  "My data",
      "All Time" :  "Total",
      "Day" :  "Day",
      "Week" :  "Week",
      "Month" :  "Month",
      "Exercise data" :  "Exercise data",
      "All data" :  "All",
      "All history" :  "All records",
      "Duration" :  "Duration",
      "Consume" :  "Consume",
      "Strength" :  "Strength",
      "Sports calendar" :  "Exercise calendar",
      "Graph" :  "Graphs",
      "Units" :  "Units",
      "All Device" :  "All devices",
      "Jump rope" :  "Jump Rope",
      "Resistance Band" :  "Resistance Band",
      "Spider Resistance Band" :  "Spider Resistance Band",
      "Dumbbell" :  "Dumbbell",
      "AB Wheel" :  "AB Wheel",
      "LeaderBoard" :  "Rank",
      "Place" :  "Place",
      "Profile" :  "Profile",
      "Settings" :  "Settings",
      "Version" :  "Version",
      "me" :  "Me",
      "Nick name" :  "Nick name",
      "Gender" :  "Gender",
      "Male" :  "Male",
      "Female" :  "Female",
      "Account amd security" :  "Account and security",
      "Choose verification method" :  "Select verification method",
      "Modify nick name" :  "Modify nick name",
      "Input nickname" :  "Input nickname",
      "Save" :  "Save",
      "Password must be between 8 and 16 characters.":  "Password must be 8-16 characters",
      "Cannot contain invalid characters.":  "No illegal characters",
      "set" :  "Numbers",
      "Lets go" :  "Lets go！",
      "Come on" :  "Go for it!",
      "My exercise data" :  "My exercise data",
      "count" :  "Exercise amount",
      "duration" :  "Exercise duration",
      "Top coach" :  "Gold coach",
      "lock" :  "Lock",
      "Unlock" :  "Unlock",
      "Speaking" :  "Broadcasting",
      "Silence" :  "Mute",
      "Select mode" :  "Select mode",
      "OTA" :  "Firmware Update",
      "Setting" :  "Setting",
      "Screen mirroring" :  "TV casting",
      "Edit" :  "Edit cards",
      "Show" :  "Show cards",
      "Hold and drag to change the order" :  "Long press to adjust the order of the cards",
      "Speak" :  "Voice Settings",
      "speak count of exercise" :  "Broadcast by exercise amount",
      "frequency" :  "Frequency",
      "Select Mode" :  "Select Mode",
      "Train Mode" :  "Please select the training mode",
      "Free mode" :  "Free mode",
      "Time training" :  "Timer counting",
      "Count training" :  "Fixed timing",
      "customize" :  "Custom",
      "select type" :  "Please select training type",
      "minute" :  "minute",
      "minutes" :  "Min",
      "Kneeling" :  "Kneeling rollout",
      "Standing" :  "Standing rollout",
      "Dumbbell curl" :  "Bicep curls",
      "Bent arm flexion and extension" :  "Bent over tricep extension",
      "Neck flexion and extension" :  "Overhead tricep extension",
      "Leaning over rowing" :  "Bent over rows",
      "Free skipping" :  "Free rope jumping",
      "Standing rowing" :  "Resistance band rows",
      "Upward curl" :  "Standard bicep curls",
      "Side lift" :  "Lateral raise",
      "Overhead flexion and extension" :  "Overhead tricep extensions",
      "Supine rowing" :  "Supine position rowing",
      "Sitting curl" :  "Seated preacher curl",
      "Seated row" :  "Seated band row",
      "Count" :  "Count",//英文count
      "Calories" :  "Calories burned",
      "Exercise intensity" :  "Exercise intensity",
      "Average speed" :  "Average speed",
      "Maximum heart rate" :  "Max heart rate",
      "Minimum heart rate" :  "Min heart rate",
      "Heart rate graph" :  "Heart rate graph",
      "Offline data has no real-time heart rate" :  "No heart rate display for offline data",
      "No real-time heart rate this time" :  "No real time heart rate recorded for this exercise",
      "Average heart rate" :  "Average heart rate",
      "Exercise records" :  "History",
      "Select all" :  "Select all",
      "Delete" :  "Delete",
      "Linked" :  "Linked",
      "None" :  "None",
      "Link" :  "Link",
      "Change" :  "Change",
      "Phone" :  "Phone",
      "Change password" :  "Change password",
      "Delete account" :  "Delete account",
      "LOG OUT" :  "LOG OUT",
      "It seems that there is no internet" :  "No internet",
      "Refresh" :  "Refresh",
      "success" :  "Operation succeeded",
      "Jump to the homepage in" :  "Countdown to home page :",
      "Return now" :  "Return now",
      "Reset password" :  "Reset password",
      "New password" :  "New password",
      "Confirm password" :  "Confirm new password",
      "Passwords do not match.Try again." :   "Passwords do not match.Try again.",
      "Mobile phone number verification" :   "Mobile phone number verification",
      "For your account security, you need to verify your phone number" :  "For your account security, you need to verify your phone number",
      "Next" :  "Next",
      "Link phone number" :  "Link phone number",
      "Link new phone number" :  "Link new phone number",
      "Link email" :  "Link email",
      "Link new email" : "Link new email",
      "E-mail verification" : "E-mail verification",
      "For your account security, you need to verify your Email" : "For your account security, you need to verify your Email",
      "power" : "Strength",
      "agility" : "Agility",
      "endurance" : "Stamina",
      "perseverance" : "Fortitude",
      "physique" : "Fitness",
      "data graph" : "Strength data graph",
      "monday" : "Mon",
      "tuesday" : "Tues",
      "wednesday" : "Wed",
      "thursday" : "Thur",
      "friday" : "Fri",
      "saturday" : "Sat",
      "sunday" : "Sun",
      "year" : "Year",
      "singleCount" : "set",
      "heartRate" : "heart rate",
      "Time must be between 1 and 60 minutes." : "Duration should be limited to 1 to 60 minutes.",
      "Count must be between 1 and 9999." : "Count should be limited to 1 to 9999.",
      "clickToLogin" : "Click to log in",
      "unloggedIn" : "Logged out",
      "notSet" : "Not set up",
      "seted" : "Set up",
      "Incorrect verification code" : "Incorrect verification code",
      "disableAccount" : "Account is disabled",
      "logoutTips" : "Logging out of your account will delete all data, are you sure to log out of your account?",
      "notSaveRecord" : "No record is kept for this exercise.",
      "isEndSport" : "End exercise",
      "registerByPhone" : "Register by mobil phone",
      "registerByEmail" : "Register by Email",
      "registerByPassword" : "Password",
      "setting" : "setting",
      "signOutTips" : "Sign out",
      "deleteRecord" : "Delete exercise record",
      "jumpRope" : "Bluetooth Jump Rope SJ100",
      "resistanceBand" : "Bluetooth Resistance Band SR100",
      "spiderBand" : "Bluetooth Spider Resistance Band SS100",
      "dumbBell" : "Bluetooth Dumbbell",
      'abWheel' : 'Bluetooth AB Wheel SW100',
      'grip' : 'Bluetooth Grip SJ200',
      'Grip' : 'Smart Grip',
      "SJ500" : "Smart Jump Rope SJ500",
      "headJumpRpoe" : "Smart Jump Rope NT930",
      "jumpRope200" : "Bluetooth Jump Rope SJ200",
      "fasciaGun" :"Fascia Gun FG100",
      "selectcountryregion" : "Select country/region",
      "validEmail" : "Enter a valid email address.",
      "Invalid number" : "Invalid number",
      "OTAtips":"Please do not switch or quit the page while OTA update.",
      "Operation failed" : "Operation failed,please try again",
    }
  };
}